In [108]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [109]:
df = pd.read_csv("/content/processed_city_day.csv")

In [110]:
df

Unnamed: 0           City        Date  PM2.5    PM10    NO    NO2  \
0           2123      Amaravati  2017-11-25  81.40  124.50  1.44  20.50   
1           2124      Amaravati  2017-11-26  78.32  129.06  1.26  26.00   
2           2125      Amaravati  2017-11-27  88.76  135.32  6.60  30.85   
3           2126      Amaravati  2017-11-28  64.18  104.09  2.56  28.07   
4           2127      Amaravati  2017-11-29  72.47  114.84  5.23  23.20   
...          ...            ...         ...    ...     ...   ...    ...   
6231       29525  Visakhapatnam  2020-06-26   7.63   32.27  5.91  23.27   
6232       29526  Visakhapatnam  2020-06-27  15.02   50.94  7.68  25.06   
6233       29527  Visakhapatnam  2020-06-28  24.38   74.09  3.42  26.06   
6234       29528  Visakhapatnam  2020-06-29  22.91   65.73  3.45  29.53   
6235       29529  Visakhapatnam  2020-06-30  16.64   49.97  4.05  29.26   

        NOx    NH3    CO    SO2      O3  Benzene  Toluene  Xylene    AQI  \
0     12.08  10.72  0.12  15.24  127.09     0.20     6.50    0.06  184.0   
1     14.85  10.28  0.14  26.96  117.44     0.22     7.95    0.08  197.0   
2     21.77  12.91  0.11  33.59  111.81     0.29     7.63    0.12  198.0   
3     17.01  11.42  0.09  19.00  138.18     0.17     5.02    0.07  188.0   
4     16.59  12.25  0.16  10.55  109.74     0.21     4.71    0.08  173.0   
...     ...    ...   ...    ...     ...      ...      ...     ...    ...   
6231  17.19  11.15  0.46   6.87   19.90     1.45     5.37    1.45   47.0   
6232  19.54  12.47  0.47   8.55   23.30     2.24    12.07    0.73   41.0   
6233  16.53  11.99  0.52  12.72   30.14     0.74     2.21    0.38   70.0   
6234  18.33  10.71  0.48   8.42   30.96     0.01     0.01    2.00   68.0   
6235  18.80  10.03  0.52   9.84   28.30     3.00    10.00    2.00   54.0   

        AQI_Bucket  
0         Moderate  
1         Moderate  
2         Moderate  
3         Moderate  
4         Moderate  
...            ...  
6231          Good  
6232          Good  
6233  Satisfactory  
6234  Satisfactory  
6235  Satisfactory  

[6236 rows x 17 columns]

In [111]:
# df["Age"].fillna(29,inplace = True)
# df["Cabin"].fillna("UNKNOWN",inplace = True)
# df["Embarked"].fillna("U",inplace = True)
# print(df.isnull().sum())

In [112]:
df["AQI_Bucket"].unique()

array(['Moderate', 'Poor', 'Very Poor', 'Satisfactory', 'Good', 'Severe'],
      dtype=object)

In [113]:
df["AQI_Bucket"]=df["AQI_Bucket"].map(lambda x:str(x).replace("Severe",'0'))
df["AQI_Bucket"]=df["AQI_Bucket"].map(lambda x:str(x).replace("Poor",'2'))
df["AQI_Bucket"]=df["AQI_Bucket"].map(lambda x:str(x).replace("Very Poor",'1'))
df["AQI_Bucket"]=df["AQI_Bucket"].map(lambda x:str(x).replace("Satisfactory",'4'))
df["AQI_Bucket"]=df["AQI_Bucket"].map(lambda x:str(x).replace("Good",'5'))
df["AQI_Bucket"]=df["AQI_Bucket"].map(lambda x:str(x).replace("Moderate",'3'))


In [114]:
stringValues = ["PM2.5","PM10","NO","NO2","NOx","NH3","CO","SO2","O3","Benzene","Toluene","Xylene"]
for i in stringValues:
  # get all unique values in a list. Index of each 
  uniqueList = list(set(df[i]))
  # Create replace dictionary with key as string to be replaced and value as integer encoding for the string
  replaceDict = {}
  for j in range(len(uniqueList)):
    replaceDict[uniqueList[j]] = j
  df = df.replace({i : replaceDict})

In [115]:
df['AQI_Bucket']=pd.to_numeric(df['AQI_Bucket'],errors="coerce")

In [116]:
df.iloc[:,[3,4,5,6,7,8,9,10,11,12,13,14,15]]

PM2.5    PM10      NO     NO2     NOx     NH3     CO     SO2      O3  \
0       84.0   116.0  1906.0    18.0  2035.0  1676.0  386.0  1165.0   123.0   
1     2689.0   119.0  1678.0    30.0  2037.0  1678.0  154.0    25.0   113.0   
2       91.0   125.0  1509.0    32.0    19.0    12.0  287.0    32.0   107.0   
3       60.0    97.0  1081.0    31.0    15.0  1677.0   80.0    18.0   134.0   
4       68.0   106.0     5.0    21.0    14.0    13.0  359.0     9.0   105.0   
...      ...     ...     ...     ...     ...     ...    ...     ...     ...   
6231  1110.0  3169.0   842.0   776.0  2160.0  2333.0   36.0  1618.0   809.0   
6232  3464.0  4873.0  1346.0  1968.0  1370.0   259.0  108.0   872.0  1714.0   
6233  4574.0  3833.0  2602.0  1972.0  1020.0  1445.0   66.0   570.0   600.0   
6234  2488.0  5275.0  2552.0  1048.0  2545.0  2245.0  374.0  1943.0  2788.0   
6235   824.0  2597.0   528.0   522.0  1667.0  2503.0   66.0     8.0  1730.0   

      Benzene  Toluene  Xylene    AQI  
0       991.0      6.0   473.0  184.0  
1       358.0    612.0   982.0  197.0  
2      1156.0    611.0   924.0  198.0  
3       135.0      5.0   704.0  188.0  
4        63.0   1928.0   982.0  173.0  
...       ...      ...     ...    ...  
6231    207.0   1787.0   196.0   47.0  
6232    838.0   1391.0   902.0   41.0  
6233    936.0   1063.0   148.0   70.0  
6234    308.0   1354.0    58.0   68.0  
6235      3.0     10.0    58.0   54.0  

[6236 rows x 13 columns]

In [117]:
X = df.iloc[:,[3,4,5,6,7,8,9,10,11,12,13,14,15]].values

In [118]:
y = pd.DataFrame(df.AQI_Bucket)

In [119]:
y = df["AQI_Bucket"].values

In [120]:
X.shape

(6236, 13)

In [121]:
y.shape

(6236,)

In [122]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=4)

In [123]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4365, 13)
(1871, 13)
(4365,)
(1871,)


In [124]:
# Initialize variables
learning_rate = 0.1
iterations = 5000
N = y_train.size

# number of input features
input_size = 13

# number of hidden layers neurons
hidden_size = 2

# number of neurons at the output layer
output_size = 1

results = pd.DataFrame(columns=["AQI","AQI_Bucket"])

In [125]:
np.random.seed(100)

# initializing weight for the hidden layer
W1 = np.random.normal(scale=0.5, size=(input_size, hidden_size))   

# initializing weight for the output layer
W2 = np.random.normal(scale=0.5, size=(hidden_size , output_size)) 

In [126]:
print(W1)
print(W2)

[[-0.87488274  0.1713402 ]
 [ 0.5765179  -0.12621802]
 [ 0.49066039  0.25710942]
 [ 0.11058983 -0.53502167]
 [-0.09474792  0.12750072]
 [-0.22901349  0.21758174]
 [-0.29179753  0.40842354]
 [ 0.3363604  -0.05220557]
 [-0.26564019  0.51486634]
 [-0.21906781 -0.55915912]
 [ 0.80949083  0.77080259]
 [-0.12593957 -0.42121787]
 [ 0.09225935  0.4685411 ]]
[[0.36550017]
 [0.68077806]]


In [127]:
print(X_train.shape)

(4365, 13)


In [128]:
W1.shape

(13, 2)

In [129]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def mean_squared_error(y_pred, y_true):
    return ((y_pred - y_true)**2).sum() / (2*y_pred.size)
    
def accuracy(y_pred, y_true):
    acc = y_pred.max() == y_true.max()
    return acc.mean()

In [130]:
print(y_train)

[0. 2. 2. ... 3. 4. 4.]


In [131]:
# df['AQI_Bucket']=pd.to_numeric(df['AQI_Bucket'],errors="coerce")

In [136]:
for itr in range(iterations):    
    
    # feedforward propagation
    # on hidden layer
    Z1 = np.dot(X_train, W1)
    A1 = sigmoid(Z1)

    # on output layer
    Z2 = np.dot(A1, W2)
    A2 = sigmoid(Z2)
    print(A2.shape)
    
    # Calculating error
    mse = mean_squared_error(A2,y_train)
    acc = accuracy(A2, y_train)
    results=results.append({"mse":mse, "accuracy":acc},ignore_index=True )
    
    # backpropagation
    E1 = A2 - y_train
    dW1 = E1 * A2 * (1 - A2)
    print(dW1)
    print( W2)
    E2 = np.dot(dW1, W2)
    dW2 = E2 * A1 * (1 - A1)

    
    # weight updates
    W2_update = np.dot(A1.T, dW1) / N
    W1_update = np.dot(X_train.T, dW2) / N

    W2 = W2 - learning_rate * W2_update
    W1 = W1 - learning_rate * W1_update

(4365, 1)
[[ 0.1423663  -0.2423765  -0.2423765  ... -0.4347479  -0.6271193
  -0.6271193 ]
 [ 0.1423663  -0.2423765  -0.2423765  ... -0.4347479  -0.6271193
  -0.6271193 ]
 [ 0.1423663  -0.2423765  -0.2423765  ... -0.4347479  -0.6271193
  -0.6271193 ]
 ...
 [ 0.14814058 -0.29812491 -0.29812491 ... -0.52125766 -0.74439041
  -0.74439041]
 [ 0.1423663  -0.2423765  -0.2423765  ... -0.4347479  -0.6271193
  -0.6271193 ]
 [ 0.14814058 -0.29812491 -0.29812491 ... -0.52125766 -0.74439041
  -0.74439041]]
[[0.36550017]
 [0.68077806]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


ValueError: ignored

In [132]:
# df['']=pd.to_numberic(df[''],errors="coerce")

AttributeError: ignored

In [ ]:
Z1 = np.dot(X_test, W1)
A1 = sigmoid(Z1)

Z2 = np.dot(A1, W2)
A2 = sigmoid(Z2)

acc = accuracy(A2, y_test)
print("Accuracy: {}".format(acc))

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [ ]:
data = load_iris()

# Get features and target
X=data.data
y=data.target

In [ ]:
y = pd.get_dummies(y).values

y[:3]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20, random_state=4)

In [ ]:
learning_rate = 0.1
iterations = 5000
N = y_train.size

# number of input features
input_size = 4

# number of hidden layers neurons
hidden_size = 2 

# number of neurons at the output layer
output_size = 3  

results = pd.DataFrame(columns=["mse", "accuracy"])

In [ ]:
np.random.seed(10)

# initializing weight for the hidden layer
W1 = np.random.normal(scale=0.5, size=(input_size, hidden_size))   

# initializing weight for the output layer
W2 = np.random.normal(scale=0.5, size=(hidden_size , output_size)) 

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def mean_squared_error(y_pred, y_true):
    return ((y_pred - y_true)**2).sum() / (2*y_pred.size)
    
def accuracy(y_pred, y_true):
    acc = y_pred.argmax(axis=1) == y_true.argmax(axis=1)
    return acc.mean()

In [ ]:
for itr in range(iterations):    
    
    # feedforward propagation
    # on hidden layer
    Z1 = np.dot(X_train, W1)
    A1 = sigmoid(Z1)

    # on output layer
    Z2 = np.dot(A1, W2)
    A2 = sigmoid(Z2)
    
    
    # Calculating error
    mse = mean_squared_error(A2, y_train)
    acc = accuracy(A2, y_train)
    results=results.append({"mse":mse, "accuracy":acc},ignore_index=True )
    
    # backpropagation
    E1 = A2 - y_train
    dW1 = E1 * A2 * (1 - A2)

    E2 = np.dot(dW1, W2.T)
    dW2 = E2 * A1 * (1 - A1)

    
    # weight updates
    W2_update = np.dot(A1.T, dW1) / N
    W1_update = np.dot(X_train.T, dW2) / N

    W2 = W2 - learning_rate * W2_update
    W1 = W1 - learning_rate * W1_update

In [ ]:
results.mse.plot(title="Mean Squared Error")

In [ ]:
results.accuracy.plot(title="Accuracy")

In [ ]:
Z1 = np.dot(X_test, W1)
A1 = sigmoid(Z1)

Z2 = np.dot(A1, W2)
A2 = sigmoid(Z2)

acc = accuracy(A2, y_test)
print("Accuracy: {}".format(acc))