In [ ]:
%cd drive/MyDrive/ML_praticals/Datasets/

/content/drive/MyDrive/ML_praticals/Datasets


#Apply Naïve Bayes Classification of the same dataset and compare using the results found.

In machine learning, Naïve Bayes classification is a straightforward and powerful algorithm for the classification task. Naïve Bayes classification is based on applying Bayes’ theorem with strong independence assumption between the features.  Naïve Bayes classification produces good results when we use it for textual data analysis such as Natural Language Processing.


Naïve Bayes models are also known as `simple Bayes` or `independent Bayes`. All these names refer to the application of Bayes’ theorem in the classifier’s decision rule. Naïve Bayes classifier applies the Bayes’ theorem in practice. This classifier brings the power of Bayes’ theorem to machine learning.


Naïve Bayes Classifier uses the Bayes’ theorem to predict membership probabilities for each class such as the probability that given record or data point belongs to a particular class. The class with the highest probability is considered as the most likely class. This is also known as the **Maximum A Posteriori (MAP)**. 

The **MAP for a hypothesis with 2 events A and B is**

**MAP (A)**

= max (P (A | B))

= max (P (B | A) * P (A))/P (B)

= max (P (B | A) * P (A))


Here, P (B) is evidence probability. It is used to normalize the result. It remains the same, So, removing it would not affect the result.


Naïve Bayes Classifier assumes that all the features are unrelated to each other. Presence or absence of a feature does not influence the presence or absence of any other feature. 


In real world datasets, we test a hypothesis given multiple evidence on features. So, the calculations become quite complicated. To simplify the work, the feature independence approach is used to uncouple multiple evidence and treat each as an independent one.


There are 3 types of Naïve Bayes algorithm. The 3 types are listed below:-

  1. Gaussian Naïve Bayes

  2. Multinomial Naïve Bayes

  3. Bernoulli Naïve Bayes

These 3 types of algorithm are explained below.

When we have continuous attribute values, we made an assumption that the values associated with each class are distributed according to Gaussian or Normal distribution. For example, suppose the training data contains a continuous attribute x. We first segment the data by the class, and then compute the mean and variance of x in each class. Let µi be the mean of the values and let σi be the variance of the values associated with the ith class. Suppose we have some observation value xi . Then, the probability distribution of xi given a class can be computed by the following equation –


![Gaussian Naive Bayes algorithm](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEWCcq1XtC1Yw20KWSHn2axYa7eY-a0T1TGtdVn5PvOpv9wW3FeA&s)

In the multivariate Bernoulli event model, features are independent boolean variables (binary variables) describing inputs. Just like the multinomial model, this model is also popular for document classification tasks where binary term occurrence features are used rather than term frequencies.




Naïve Bayes is one of the most straightforward and fast classification algorithm. It is very well suited for large volume of data. It is successfully used in various applications such as :

1. Spam filtering
2. Text classification
3. Sentiment analysis
4. Recommender systems

It uses Bayes theorem of probability for prediction of unknown class.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = 'city_day.csv'
df = pd.read_csv(data).dropna()
df.iloc[:,[2,3,4,5,6,7,8,9,10]]

PM2.5    PM10    NO    NO2    NOx    NH3    CO    SO2      O3
2123   81.40  124.50  1.44  20.50  12.08  10.72  0.12  15.24  127.09
2124   78.32  129.06  1.26  26.00  14.85  10.28  0.14  26.96  117.44
2125   88.76  135.32  6.60  30.85  21.77  12.91  0.11  33.59  111.81
2126   64.18  104.09  2.56  28.07  17.01  11.42  0.09  19.00  138.18
2127   72.47  114.84  5.23  23.20  16.59  12.25  0.16  10.55  109.74
...      ...     ...   ...    ...    ...    ...   ...    ...     ...
29525   7.63   32.27  5.91  23.27  17.19  11.15  0.46   6.87   19.90
29526  15.02   50.94  7.68  25.06  19.54  12.47  0.47   8.55   23.30
29527  24.38   74.09  3.42  26.06  16.53  11.99  0.52  12.72   30.14
29528  22.91   65.73  3.45  29.53  18.33  10.71  0.48   8.42   30.96
29529  16.64   49.97  4.05  29.26  18.80  10.03  0.52   9.84   28.30

[6236 rows x 9 columns]

In [ ]:
df

City        Date  PM2.5    PM10    NO    NO2    NOx    NH3  \
2123       Amaravati  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72   
2124       Amaravati  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28   
2125       Amaravati  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91   
2126       Amaravati  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42   
2127       Amaravati  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25   
...              ...         ...    ...     ...   ...    ...    ...    ...   
29525  Visakhapatnam  2020-06-26   7.63   32.27  5.91  23.27  17.19  11.15   
29526  Visakhapatnam  2020-06-27  15.02   50.94  7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38   74.09  3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91   65.73  3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64   49.97  4.05  29.26  18.80  10.03   

         CO    SO2      O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket  
2123   0.12  15.24  127.09     0.20     6.50    0.06  184.0      Moderate  
2124   0.14  26.96  117.44     0.22     7.95    0.08  197.0      Moderate  
2125   0.11  33.59  111.81     0.29     7.63    0.12  198.0      Moderate  
2126   0.09  19.00  138.18     0.17     5.02    0.07  188.0      Moderate  
2127   0.16  10.55  109.74     0.21     4.71    0.08  173.0      Moderate  
...     ...    ...     ...      ...      ...     ...    ...           ...  
29525  0.46   6.87   19.90     1.45     5.37    1.45   47.0          Good  
29526  0.47   8.55   23.30     2.24    12.07    0.73   41.0          Good  
29527  0.52  12.72   30.14     0.74     2.21    0.38   70.0  Satisfactory  
29528  0.48   8.42   30.96     0.01     0.01    0.00   68.0  Satisfactory  
29529  0.52   9.84   28.30     0.00     0.00    0.00   54.0  Satisfactory  

[6236 rows x 16 columns]

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('city_day.csv').dropna()
x = dataset.iloc[:, [2,3,4,5,6,7,8,9,10]].values
y = dataset.iloc[:, -1].values

In [ ]:
len(x)==len(y)

True

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)



In [ ]:

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)

In [ ]:
print(ac)
print(cm)

0.7604166666666666
[[ 86   0   0  11   0   0]
 [  0 388  32  80   0   1]
 [  0  29  96   0   0   6]
 [ 71  38   0 289   0   1]
 [  0   0   0   0  31   2]
 [  0   0  21   0   7  59]]


#Bernorlies

In [62]:
from sklearn.naive_bayes import BernoulliNB

In [64]:
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

In [65]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)

In [66]:
print(ac)
print(cm)

0.6057692307692307
[[  0   1   0  96   0   0]
 [  0 304  55 120   0  22]
 [  0  35  29   1   0  66]
 [  0  35   0 364   0   0]
 [  0   2   3   0   0  28]
 [  0   4  24   0   0  59]]
